model: 
  type: VanillaVAE
data: 
  random_seed: 1
model_params: 
  latent_dim: 128
training_params: 
  epochs: 500
  batch_size: 256
  log_interval: 10 # number of batches to wait until logging the training status 
  learning_rate: 0.0001
  beta: 0.01
output: 
  output_folder: results/VanillaVAE_dropna
runtime_config: 
  accelerator: True # True means try to use GPU