# This is the config file for the mm-vae 
model: 
  type: CGMVAE
  latent_dim: 5
data: 
  random_seed: 50
  dataset: DIET
  data_path: '/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/train_data_with_cfc_5bins.csv'
training_params: 
  epochs: 10
  batch_size: 128
  log_interval: 10 # number of batches to wait until logging the training status 
  gmm_centers: '/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/results_DIET/5_gmm_center_5dims.csv'
  gmm_std: 2
  learning_rate: 0.001
loss_params: 
  data_loss_weight: 1
  kl_weight: 5
output: 
  output_folder: results_DIET/CGMVAE_cfc_cond_5bins_5dim_testing
runtime_config: 
  accelerator: True # True means try to use GPU
