data: 
  latent_variable_path: '/Users/racheliritani/Desktop/AD Project/mm-vae/cfc/cgmvae_cfc_cond_5bin_5dim_epoch5000/latent_variables_5000epochs.csv'
  label_type: cfc
  data_type: latent
  path: '/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/cfc_data_filtered.csv'
  #path: '/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/ymaze_speed_data_cleaned.csv'
  #path: '/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/ymaze_distance_data_cleaned.csv'
  #path: '/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/ymaze_alt_data_cleaned.csv'
training_params: 
  epochs: 10
  batch_size: 64
  learning_rate: 0.001
  num_k_folds: 5
model_params: 
  input_size: 2
  hidden_size: 10
  output_size: 1
  latent_dim: 5
output: 
  output_folder: results_DIET/CGMVAE_cfc_cond_5bins_5dim/mlp_15000/TestRun
runtime_config: 
  accelerator: True # True means try to use GPU